title: QDP-Blog
description: "The QuesoDiPesto Blog For Hackers"
author:
  name: "QuesoDiPesto"
  email: ""
  url: "https://quesodipesto.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "QuesoDiPesto"
year : "2021"
